# NAME = library_1.so

# SOURCE = game_graphic.cpp
# OBJECT = $(SOURCE:.cpp=.o)

# CPP ?= clang++
# CPP_FLAGS ?= -Wall -Wextra -Werror 
# CPP_FLAGS += -I../include -Iglfw/include -fPIC

# LD_FLAGS = -shared -undefined dynamic_lookup
# LD_FLAGS += -Lglfw/lib
# LD_FLAGS += -lglfw -ldl -lpthread

# all: $(NAME)

# $(NAME): $(OBJECT)
# 	$(CPP) $(LD_FLAGS) -o $(NAME) $(OBJECT)

# %.o: %.cpp
# 	@mkdir -p $(@D)
# 	$(CPP) $(CPP_FLAGS) -o $@ -c $<

# clean:
# 	rm -rf $(OBJECT)

# fclean: clean
# 	rm -rf $(NAME)

# re: fclean all

